### PR TITLE
preloader animation fixed

### PR DESCRIPTION
**Pull request by shashwatdwi176**

### CODE REVIEW

**Comment by shashwatdwi176** [comment]
#18 issue fixed

**Comment by k3yss** [comment]
The implementation works fine but your PR is unreadable because you have wrapped everything inside a new div which messes up the indentation, why not fix the previous implementation...can you try doing that?

**Comment by shashwatdwi176** [comment]
Sorry sir , this is my first live project and that's why this happened. Sir
I have tried my best to make the preloader without that div tag  but the
problem is the background colour was loading correctly but the text and the
moscot gif was loading with the content of the website that's why I have to
add that div tag.

**Comment by k3yss** [comment]
DW It's fine, for me to review your MR you can follow these steps:
* Make changes
* Don't run the `npx prettier --write .` command
* run `git diff` to see the changes you have made. Make sure this time you make the pull request with only the lines changed, the maintainers will indent the code
* Once you think it can be reviewed make another Pull request or make commits to this one fixing the indentation

**Pull request closed without merging**
